#ifndef SIDEWALKDEFAULTS_H__
#define SIDEWALKDEFAULTS_H__

#include "c4d.h"


// General parameters
const Vector DEF_SIDEWALK_ELEMENT_SIZE(30.0, 7.5, 30.0);
const Float DEF_SIDEWALK_COUNT_X = 8;
const Float DEF_SIDEWALK_COUNT_Z = 20;
const Float DEF_SIDEWALK_SHIFT = 15.0;
const Float DEF_SIDEWALK_ELEMENT_SELBIAS = -0.5;
const Int32 DEF_SIDEWALK_ELEMENT_SEED = 7979;

// Plates
const Float DEF_SIDEWALK_PLATES_SPACE = 0.75;
const Float DEF_SIDEWALK_PLATES_FILLET_RAD = 0.5;
const Int32 DEF_SIDEWALK_PLATES_FILLET_SUBD = 5;
const Bool DEF_SIDEWALK_PLATES_PHONG = true;
const Vector DEF_SIDEWALK_PLATES_RND_ROT(Rad(5.0), Rad(2.0), Rad(2.0));
const Vector DEF_SIDEWALK_PLATES_RND_POS(0.0, 2.0, 0.0);
const Int32 DEF_SIDEWALK_PLATES_RND_SEED = 123;
const Float DEF_SIDEWALK_PLATES_MAT_SCALE = 1.0;

// Cobblestones
const Int32 DEF_SIDEWALK_COBBLE_COUNT = 4;
const Int32 DEF_SIDEWALK_COBBLE_SUBD = 4;
const Float DEF_SIDEWALK_COBBLE_CRUMPLE = 0.4;
const Float DEF_SIDEWALK_COBBLE_SPACE = 0.5;
const Float DEF_SIDEWALK_COBBLE_FILLET_RAD = 1.0;
const Int32 DEF_SIDEWALK_COBBLE_FILLET_SUBD = 2;
const Bool DEF_SIDEWALK_COBBLE_PHONG = true;
const Vector DEF_SIDEWALK_COBBLE_RND_ROT(Rad(10.0), Rad(5.0), Rad(5.0));
const Vector DEF_SIDEWALK_COBBLE_RND_POS(0.5, 2.0, 0.5);
const Int32 DEF_SIDEWALK_COBBLE_RND_SEED = 321;
const Float DEF_SIDEWALK_COBBLE_MAT_SCALE = 1.0;

// Dirt Plane
const Bool DEF_SIDEWALK_USE_DIRT = true;
const Int32 DEF_SIDEWALK_DIRT_SUBD = 5;
const Float DEF_SIDEWALK_DIRT_CRUMPLE = 0.1;
const Float DEF_SIDEWALK_DIRT_ELEVATION = 3.25;
const Int32 DEF_SIDEWALK_DIRT_SEED = 4567;
const Float DEF_SIDEWALK_DIRT_MAT_SCALE = 1.0;

// Curbstones
const Bool DEF_SIDEWALK_USE_CURB = true;
const Int32 DEF_SIDEWALK_CURB_COUNT = 8;
const Float DEF_SIDEWALK_CURB_SIZE_X = 15.0;
const Float DEF_SIDEWALK_CURB_SIZE_Y = 15.0;
const Float DEF_SIDEWALK_CURB_VARIATION = 0.25;
const Int32 DEF_SIDEWALK_CURB_VARIATION_SEED = 9876;
const Float DEF_SIDEWALK_CURB_CRUMPLE_VAL = 0.1;
const Float DEF_SIDEWALK_CURB_ELEVATION = 1.0;
const Int32 DEF_SIDEWALK_CURB_SUBD = 8;
const Float DEF_SIDEWALK_CURB_FILLET_RAD = 1.5;
const Int32 DEF_SIDEWALK_CURB_FILLET_SUBD = 2;
const Float DEF_SIDEWALK_CURB_MAT_SCALE = 1.0;



#endif // SIDEWALKDEFAULTS_H__
